# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  
- task: Npm@1
  displayName: 'install npm'
  inputs:
    command: install

- script: sudo npm install -g typescript
  displayName: 'npm install typescript'

- bash: sudo yarn install --production=true
  displayName: 'Install dependencies (yarn)'
  workingDirectory: Server/Post2Push

- bash: sudo npm install -S @types/node
  displayName: 'Install node types'
  workingDirectory: Server/Post2Push

- script: tsc --project Server/Post2Push
  displayName: 'Compile TypeScript'

- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    customCommand: 'test'
    workingDir: Server/Post2Push

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for JavaScript'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

- task: DeleteFiles@1
  displayName: 'delete ts source'
  inputs:
    contents: **\*.ts

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1